# Generated by Django 4.0.4 on 2022-05-25 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_des_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='vids'),
            preserve_default=False,
        ),
    ]
