# Generated by Django 4.0.4 on 2022-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_destination_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='video',
        ),
        migrations.AddField(
            model_name='destination',
            name='duration',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
