# Generated by Django 4.0.4 on 2022-06-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompId', models.CharField(max_length=3)),
                ('Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'CRUD',
            },
        ),
    ]
