# Generated by Django 4.0.4 on 2022-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='CompId',
            field=models.CharField(max_length=10),
        ),
    ]
