# Generated by Django 4.0.4 on 2022-07-01 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODOLIST', '0002_alter_complain_compid'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
    ]
