# Generated by Django 4.0.4 on 2022-07-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0003_complain_user_alter_complain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='solution',
            field=models.CharField(default='abc', max_length=1000),
        ),
    ]
