# Generated by Django 4.0.4 on 2022-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0004_complain_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='solution',
            field=models.CharField(default='no solution yet!', max_length=1000),
        ),
    ]
