# Generated by Django 4.0.4 on 2022-07-04 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0005_alter_complain_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='solution',
        ),
    ]
