# Generated by Django 4.0.4 on 2022-07-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0007_complain_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='solution',
        ),
        migrations.CreateModel(
            name='Sclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(default='no solution yet!', max_length=1000)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TODOLIST.complain')),
            ],
        ),
    ]
