# Generated by Django 4.0.4 on 2022-07-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0008_remove_complain_solution_sclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sclass',
            old_name='complain',
            new_name='complain1',
        ),
    ]
