# Generated by Django 4.0.4 on 2022-07-12 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TODOLIST', '0009_rename_complain_sclass_complain1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sclass',
            name='complain1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TODOLIST.complain'),
        ),
        migrations.AlterField(
            model_name='sclass',
            name='solution',
            field=models.CharField(default='no solution yet!', max_length=1000, null=True),
        ),
    ]
